jdk: openjdk11
language: java
bundler_args: --retry 2

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "PohRAmuiClPsRnpqFLBdh9rF0DiRkSjF82VIVgHWS7GHVagjzrkflpG2OAz6XlI5JIOdivQlMYCtswF3QIXD2YRvRipS4zM/NySacG+DPmRKlJIvUSpa6G2wnf2rmIf/KlKpU5bmgVoiJSzUDcQBJcjRqQSHpHg7pkb/vR3seHs8Bfd1H9wDHSck+KeqCruq/RdTFid66FVvvw8hwu1HXqd4/2g3s/iX/PkIk1Qrtn0GK9GoeLsmwwrGkuSSZG1Z2TPgWcSFU6gUwYEokJ8njstB3L85JSsOgDmArsB9zdDziHDDZw/AD5eExBpBjiLsAQrLhSpR4FuPEo+Tm20CnELE8eb13qKnoclzHt426ZvSYdMBeY1N7EhvxFShy2rOBPnqaV+1SYNzoW94g0ShcArXoXsYn+9cmvMdsE7dYlBfYLmG1Ej5n3jLeO5uAokCgEpG25sWDRMnncBM5IITjpdqAoxRrQjAFhGLNFKtn4nlBdWXaV1fBvhOv8pxZe3CcWPZIuPg+Co+Ss4zyAIzeBJJkb2eclLOHoOqiQrlCgbi5FKNoQRakHCyC04HGC14Q2uQhD7fQg6WZ7iuvwDxqk1SQeWvR6wG1Jjgxoc33KqVZDD2Jxtvl6vqMjTjMzozpf3iimOf//ba5qJb5Cs9rskg0DwYMxWnN+Kmlz0DZg8="

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

services:
  - docker

before_install:
  - gem install deb-s3
    
script:
  - set -e
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - cp ./target/*.deb ./target/it-tests
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud ./target/it-tests
  - docker run --privileged=true --name r2cloud -d --tty r2cloud
  - docker exec r2cloud /home/pi/r2cloud-tests/bin/start-tests.sh
  - sh deploy.sh
