language: java
bundler_args: --retry 2

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "DR4CV6DpNPVh9YkAPIDeBWgsIEKlo0pZh/FSJIePdtQTAbX6Wr4D1yZ/U+9Ji8TeRU1Dw0KR3DQ7cRbesGCMCyuAOADWnvhGs8hWtULo/tvHdNmKA6z05U5xuQ7y8JpkNBWTA0mE6iFyWaMdLgIgPAQobmzgJKzArofUqqs/z71EIu+DhTvtE8Mlb0pzzLgfM94NrNkNQVtKEXLpQph8+1/y+iV1ktaL/wHWuS5bX+6yWrwCtzbP0SWi1K6qWzGYfWa5yUB7nRqaLrjXxiD+iG3DPMCi39n3yx0HgrJdgBLpz0CjpzxWC2uVSD+4H6tMHzHRW+nqXEM24ajy1XJ2B15TJOUv6UfQOTLWs3NSJMP8RQVGVd5zyP+jjvdRX7N6GZjSImzNhD/BLzEK+UdRZmi7UkCUSs/vWcO0gGt2V0dXoOy4cLJO28akxPou4IBS8MXOYDapcxkhOE9o3h3n0ie/NdljaT4eNZO9fKoPEeL9UHrtHAefS+65Yzz1SgdCqDQIaNt27DBdi1q4/eiS7mQ9o4KKbgKYVbk5CYWdsfOLes2+7Foz7woX6xSeD1UiPEdyNGCPlXzR7j2CnB0VOjWYgQhjVUp6MjTMOOzbZCC9rmbOP6NALz2AmxJt64l7TXZ/z8zs/+gZwlZrZisBbPcjDUxRFRAA2qevGKtvYMQ="

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

services:
  - docker

before_install:
  - gem install deb-s3
    
script:
  - set -e
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - cp ./target/*.deb ./target/it-tests
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud ./target/it-tests
  - docker run --privileged=true --name r2cloud -d --tty r2cloud
  - docker exec r2cloud /home/pi/r2cloud/bin/start-tests.sh
  - sh deploy.sh
